default: true

# Enforce line length globally; use file/task-specific disables where required
# via markdownlint-disable chunks near the affected sections.

# Permit duplicate headings at different levels/siblings only
MD024:
  siblings_only: true

# Heading punctuation rules (common sentence punctuation)
MD026:
  punctuation: ".,;:!"

# Allow first line not to be a top-level heading (some docs start with metadata)
MD041: false

# Code block style
MD046:
  style: fenced

# Inline code spans: allow backticks in text without strict checks
MD038: false

# Ordered list item prefix flexible (allow any numbering)
MD029: false

# Allow inline HTML (used in some docs)
MD033: false
