apiVersion: v1
kind: Namespace
metadata:
  name: work-queue

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: work-queue

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: work-queue
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: redis-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: redis
        image: redis:7-alpine@sha256:0302cccee2b2043e61b497c8f4075467c5f7ba27a9f38be7e092634f2734baed
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
        command:
          - redis-server
          - --appendonly
          - "yes"
          - --save
          - "60 1"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h 127.0.0.1 -p 6379 ping"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h 127.0.0.1 -p 6379 ping"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-tmp
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: work-queue
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
