apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-api-alerts
  namespace: redis-work-queue
data:
  alerts.yaml: |
    groups:
    - name: admin-api
      interval: 30s
      rules:
      - alert: AdminAPIDown
        expr: up{job="admin-api"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Admin API is down"
          description: "Admin API instance {{ $labels.instance }} has been down for more than 5 minutes"

      - alert: AdminAPIHighErrorRate
        expr: rate(http_requests_total{job="admin-api",status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on Admin API"
          description: "Admin API is experiencing {{ $value | humanizePercentage }} error rate"

      - alert: AdminAPIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="admin-api"}[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High latency on Admin API"
          description: "95th percentile latency is {{ $value }}s"

      - alert: AdminAPIRateLimitExhausted
        expr: rate(rate_limit_exceeded_total{job="admin-api"}[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Rate limit being hit frequently"
          description: "Rate limit is being exceeded {{ $value }} times per second"

      - alert: AdminAPIAuditLogFailure
        expr: increase(audit_log_errors_total{job="admin-api"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Audit log write failures"
          description: "Failed to write {{ $value }} audit log entries"

      - alert: AdminAPIMemoryUsage
        expr: container_memory_usage_bytes{pod=~"admin-api-.*"} / container_spec_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Admin API pod {{ $labels.pod }} is using {{ $value | humanizePercentage }} of memory limit"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-api-dashboards
  namespace: redis-work-queue
data:
  dashboard.json: |
    {
      "dashboard": {
        "title": "Admin API Monitoring",
        "panels": [
          {
            "title": "Request Rate",
            "targets": [
              {
                "expr": "rate(http_requests_total{job='admin-api'}[5m])"
              }
            ]
          },
          {
            "title": "Error Rate",
            "targets": [
              {
                "expr": "rate(http_requests_total{job='admin-api',status=~'5..'}[5m])"
              }
            ]
          },
          {
            "title": "P95 Latency",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job='admin-api'}[5m]))"
              }
            ]
          },
          {
            "title": "Active Connections",
            "targets": [
              {
                "expr": "http_connections_active{job='admin-api'}"
              }
            ]
          },
          {
            "title": "Rate Limit Hits",
            "targets": [
              {
                "expr": "rate(rate_limit_exceeded_total{job='admin-api'}[5m])"
              }
            ]
          },
          {
            "title": "Audit Log Writes",
            "targets": [
              {
                "expr": "rate(audit_log_writes_total{job='admin-api'}[5m])"
              }
            ]
          }
        ]
      }
    }