version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app-all:
    build: ..
    depends_on:
      - redis
    command: ["/job-queue-system", "--role=all", "--config=/config/config.yaml"]
    volumes:
      - ../config:/config:ro
    ports:
      - "9090:9090"

  app-worker:
    build: ..
    depends_on:
      - redis
    command: ["/job-queue-system", "--role=worker", "--config=/config/config.yaml"]
    volumes:
      - ../config:/config:ro

  app-producer:
    build: ..
    depends_on:
      - redis
    command: ["/job-queue-system", "--role=producer", "--config=/config/config.yaml"]
    volumes:
      - ../config:/config:ro

