roles:
  viewer:
    name: "Viewer"
    description: "Read-only access to stats and job lists"
    permissions:
      - "stats:read"
      - "queues:read"
      - "jobs:read"
      - "workers:read"
    resource_constraints:
      queues: ["*"]
      environment: ["staging", "production"]

  operator:
    name: "Operator"
    description: "Basic operations including job enqueuing"
    inherits: ["viewer"]
    permissions:
      - "jobs:enqueue"
      - "jobs:retry"
      - "queues:list"
      - "bench:run"
    resource_constraints:
      queues: ["*"]
      environment: ["staging", "production"]

  maintainer:
    name: "Maintainer"
    description: "Advanced operations including DLQ management"
    inherits: ["operator"]
    permissions:
      - "dlq:read"
      - "dlq:retry"
      - "dlq:export"
      - "jobs:cancel"
      - "jobs:priority"
      - "queues:create"
      - "workers:manage"
    resource_constraints:
      queues: ["*"]
      environment: ["staging", "production"]

  admin:
    name: "Administrator"
    description: "Full administrative access"
    inherits: ["maintainer"]
    permissions:
      - "dlq:purge"
      - "queues:delete"
      - "admin:*"
      - "system:*"
    resource_constraints:
      queues: ["*"]
      environment: ["*"]

  # Specialized roles for specific use cases
  ci-pipeline:
    name: "CI/CD Pipeline"
    description: "Limited access for automated systems"
    permissions:
      - "jobs:enqueue"
      - "stats:read"
      - "jobs:read"
    resource_constraints:
      queues: ["test-*", "staging-*"]
      environment: ["staging"]
      schedule: "always"

  monitoring:
    name: "Monitoring System"
    description: "Read-only access for monitoring and alerting"
    permissions:
      - "stats:read"
      - "stats:export"
      - "metrics:read"
      - "health:read"
    resource_constraints:
      queues: ["*"]
      environment: ["*"]
      schedule: "always"

  emergency:
    name: "Emergency Response"
    description: "Emergency access for incident response"
    permissions:
      - "admin:all"
      - "emergency:*"
    resource_constraints:
      queues: ["*"]
      environment: ["*"]
      conditions:
        - "incident_declared"
        - "after_hours"

default_role: "viewer"
role_assignment_rules:
  - domain: "company.com"
    default_role: "viewer"
  - domain: "devops.company.com"
    default_role: "operator"
  - domain: "admin.company.com"
    default_role: "admin"