# RBAC Token Service Configuration
server:
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576

# Token configuration
token:
  format: "jwt"  # jwt or paseto
  default_ttl: 24h
  max_ttl: 168h  # 7 days
  issuer: "redis-work-queue-rbac"
  audience: "admin-api"
  allow_refresh: true
  refresh_ttl: 168h

# Key management
keys:
  rotation_interval: 720h  # 30 days
  grace_period: 24h
  algorithm: "HS256"
  key_size: 256
  storage:
    type: "file"
    connection: "/app/keys"
    encryption_key: "${RBAC_KEY_ENCRYPTION_KEY}"

# Audit logging
audit:
  enabled: true
  log_path: "/app/audit/token-service-audit.log"
  rotate_size: 104857600  # 100MB
  max_backups: 10
  compress: true
  retention_days: 90
  filter_sensitive: true
  include_bodies: false

# Authorization
authz:
  default_deny: true
  cache_enabled: true
  cache_ttl: 5m
  roles_file: "/app/configs/roles.yaml"
  resources_file: "/app/configs/resources.yaml"
  dynamic_roles: false

# Redis connection for token validation and user data
redis:
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  password: "${REDIS_PASSWORD}"
  db: 1  # Use different DB for RBAC data
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 10
  window: 1m

# CORS settings
cors:
  enabled: true
  allowed_origins:  # Provided via env vars per environment
    - "${CORS_ALLOWED_ORIGIN_LOCAL:-http://localhost:3000}"
    - "${CORS_ALLOWED_ORIGIN_STAGING:-}"
    - "${CORS_ALLOWED_ORIGIN_PROD:-}"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-API-Token"
    - "X-Request-ID"
  allow_credentials: true
  max_age: 86400

# Logging
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Health check configuration
health:
  enabled: true
  path: "/health"

# Metrics configuration
metrics:
  enabled: true
  path: "/metrics"
  port: 8081

# Startup validation to enforce required secrets
startup_validation:
  fail_fast: true
  required_env_vars:
    - RBAC_KEY_ENCRYPTION_KEY
    - REDIS_PASSWORD

# Security headers
security:
  headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"
    content_security_policy: "default-src 'self'"
