name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true
      - name: Tidy
        run: go mod download
      - name: Govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.25.x'
          vulncheck-version: 'v1.1.3'
      - name: Tidy
        run: go mod tidy
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./...
      - name: Test
        env:
          E2E_REDIS_ADDR: localhost:6379
        run: go test ./... -race -count=1
      - name: E2E determinism (5x)
        env:
          E2E_REDIS_ADDR: 127.0.0.1:6379
        run: |
          set -euo pipefail
          for i in {1..5}; do
            echo "Run #$i"
            go test ./test/e2e -run TestE2E_WorkerCompletesJobWithRealRedis -race -count=1
          done
      - name: Govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          $(go env GOPATH)/bin/govulncheck ./...
