name: Markdown Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: .markdownlint.yaml
          globs: |
            **/*.md
            !**/node_modules/**
