name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Build binary
        run: |
          make tidy
          make build VERSION=${GITHUB_REF_NAME}
      - name: Docker build
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME} -t ghcr.io/${{ github.repository }}:latest .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository }}:latest
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

