name: Update Progress Bars

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-progress:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Recompute weighted progress
        run: |
          python3 scripts/update_progress.py

      - name: Commit changes (if any)
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/features-ledger.md README.md
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "ci: update progress bars and KLoC [skip ci]"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push commit
        if: steps.commit.outputs.changed == 'true'
        run: |
          git push

